# Generated by Django 3.1.3 on 2021-06-24 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='last',
            new_name='last_name',
        ),
    ]
