# Generated by Django 3.1.3 on 2021-06-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20210624_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='arquivo',
            field=models.FileField(default='', upload_to='pdf/'),
            preserve_default=False,
        ),
    ]
